GET https://localhost:5001/api/hello

###

GET https://localhost:5001/api/user

Authorization: "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJSTmhBQWprS054YjRhQWhERDNvLUEiLCJ0eXAiOiJhdCtqd3QifQ.eyJuYmYiOjE1OTE5NDMxOTYsImV4cCI6MTU5MTk0Njc5NiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo2MDAwIiwiYXVkIjoiYXBpIiwiY2xpZW50X2lkIjoiY2xpZW50X2lkIiwic2NvcGUiOlsiYXBpIl19.ohbNvR7vFQofBYdQFxBIJtEmmil6bcMev-cx4L7SrYU94nzSDiRPteOAcb9mJHwQw9bjtgqH8GV8achxmjey6llXbyd5fVuHHlaCurmq3UMsM3EH9m4T0jwkDj8RbDaK2APnEAde8VpyAC9WKoBKKcMuvZ4hkBLE5787b4HcO1Yp67EqlfJlM_cTF37iYVwHc5x09b32jT8G4-HJn6zKzjOTqTUd3AGgTMrS90vMU5ozo0K228PTv7M5z2sYp5iRU2Cl5koAoeUhr4DNsv6FD2wP359QRGBNe4zFMObB_M62ODejJmglHGWXiXABJ0zNpxA9yCnRb2hVpB5FgzdTMg"
